# Generated by Django 2.2 on 2019-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20190423_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='dataCriacao',
            field=models.DateTimeField(verbose_name='dataCriacao'),
        ),
    ]
