# Generated by Django 2.2 on 2019-04-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_auto_20190423_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='dataCriacao',
        ),
    ]
